// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ5JFff9D0n2H1g28mwaT6p8xW1dcazlM',
    appId: '1:1038393340751:web:a8015aae16405997898b3a',
    messagingSenderId: '1038393340751',
    projectId: 'vokitoki-872c8',
    authDomain: 'vokitoki-872c8.firebaseapp.com',
    storageBucket: 'vokitoki-872c8.firebasestorage.app',
    measurementId: 'G-8WX9HYJXGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFCqMastuTlIDGV2-DzCgtUCcos11uc0',
    appId: '1:1038393340751:android:31f50adc0bc61981898b3a',
    messagingSenderId: '1038393340751',
    projectId: 'vokitoki-872c8',
    storageBucket: 'vokitoki-872c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_lBIgc65nRN3fRyH0mF1PQf30mfj1Us',
    appId: '1:1038393340751:ios:54728ce9860a2388898b3a',
    messagingSenderId: '1038393340751',
    projectId: 'vokitoki-872c8',
    storageBucket: 'vokitoki-872c8.firebasestorage.app',
    iosBundleId: 'com.example.vokitoki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_lBIgc65nRN3fRyH0mF1PQf30mfj1Us',
    appId: '1:1038393340751:ios:54728ce9860a2388898b3a',
    messagingSenderId: '1038393340751',
    projectId: 'vokitoki-872c8',
    storageBucket: 'vokitoki-872c8.firebasestorage.app',
    iosBundleId: 'com.example.vokitoki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ5JFff9D0n2H1g28mwaT6p8xW1dcazlM',
    appId: '1:1038393340751:web:c89eaf00b81022a3898b3a',
    messagingSenderId: '1038393340751',
    projectId: 'vokitoki-872c8',
    authDomain: 'vokitoki-872c8.firebaseapp.com',
    storageBucket: 'vokitoki-872c8.firebasestorage.app',
    measurementId: 'G-4Q5CF6YHX7',
  );
}
